[package]
name = "rust_sdl"
version = "0.1.0"
edition = "2021"
build = "build.rs"
[dependencies]
specs = "0.20.0"
specs-derive = "0.4.1"
rayon = "1.10.0"
rand = "0.8.5"
[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["image"]
